# Generated by Django 5.0.3 on 2024-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecto_app', '0002_alter_education_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='Lieu_fonctionnement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='langues',
            name='Langue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='nom_Skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
