# Generated by Django 5.0.3 on 2024-03-27 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_complet', models.CharField(max_length=100)),
                ('Email_utilisateur', models.EmailField(max_length=254, unique=True)),
                ('Password_utilisateur', models.CharField(max_length=100)),
                ('photo_profile', models.URLField(blank=True, null=True)),
                ('Description_profile', models.TextField(blank=True, null=True)),
                ('Etat_compte', models.CharField(default='active', max_length=50)),
                ('Etat_profile', models.CharField(default='public', max_length=50)),
                ('Nombre_amis', models.IntegerField(default=0)),
                ('Sexe_utilisateur', models.CharField(max_length=10)),
                ('role', models.CharField(default='user', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
