# Generated by Django 5.0.3 on 2024-03-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Professeur', 'Professeur'), ('Entreprise', 'Entreprise')], default='Etudiant', max_length=100),
        ),
    ]
