# Generated by Django 5.0.3 on 2024-03-27 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_utilisateur_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='Email_utilisateur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Nom_complet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Password_utilisateur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
