# Generated by Django 5.0.3 on 2024-03-28 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_utilisateur_email_utilisateur_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
