# Generated by Django 5.0.3 on 2024-03-28 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0004_delete_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profile', models.ImageField(null=True, upload_to='etudPhotos')),
                ('Description_profile', models.CharField(max_length=60, null=True)),
                ('Etat_compte', models.CharField(choices=[('active', 'Active'), ('bloque', 'Bloqué'), ('banni', 'Banni')], default='active', max_length=50)),
                ('Etat_profile', models.CharField(choices=[('publique', 'Publique'), ('privee', 'Privée')], default='publique', max_length=50)),
                ('Nombre_amis', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
