# Generated by Django 5.0.3 on 2024-03-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='user_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
