# Generated by Django 5.0.3 on 2024-03-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_utilisateur_email_utilisateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image_publication', models.URLField(blank=True, null=True)),
                ('Etat_publication', models.CharField(default='Active', max_length=50)),
                ('Nombre_like', models.IntegerField(default=0)),
                ('Nombre_partage', models.IntegerField(default=0)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_commentaire', models.TextField()),
                ('date_commentaire', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.utilisateur')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.publication')),
            ],
        ),
    ]
