# Generated by Django 5.0.3 on 2024-03-29 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_publication_commentaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_commentaire', to='myApp.utilisateur'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_Publication', to='myApp.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
