# Generated by Django 5.0.3 on 2024-03-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_commentaire_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
