# Generated by Django 5.0.3 on 2024-03-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_utilisateur_favoris_utilisateur_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='localisation',
        ),
    ]
