# Generated by Django 5.0.3 on 2024-03-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_remove_utilisateur_localisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='favoris',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='joined',
        ),
    ]
