# Generated by Django 5.0.3 on 2024-03-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_remove_utilisateur_favoris_remove_utilisateur_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='Description_profile',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
