# Generated by Django 5.0.3 on 2024-03-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_utilisateur_description_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='Description_profile',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
