# Generated by Django 5.0.3 on 2024-03-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_utilisateur_image_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/images/'),
        ),
    ]
