# Generated by Django 5.0.3 on 2024-03-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_alter_utilisateur_photo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='document_publication',
            field=models.FileField(blank=True, null=True, upload_to='publication_documents/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='video_publication',
            field=models.FileField(blank=True, null=True, upload_to='publication_videos/'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.utilisateur'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.utilisateur'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image_publication',
            field=models.ImageField(blank=True, null=True, upload_to='publication_images/'),
        ),
    ]
