# Generated by Django 5.0.3 on 2024-04-01 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_alter_utilisateur_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='document_publication',
            field=models.FileField(blank=True, null=True, upload_to='publication_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='video_publication',
            field=models.FileField(blank=True, null=True, upload_to='publication_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'mp4', 'avi', 'mov'])]),
        ),
    ]
