# Generated by Django 5.0.3 on 2024-04-01 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_alter_publication_image_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image_publication',
            field=models.ImageField(blank=True, null=True, upload_to='publication_images'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='video_publication',
            field=models.FileField(blank=True, null=True, upload_to='publication_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'mp4', 'avi', 'mov'])]),
        ),
    ]
