# Generated by Django 5.0.3 on 2024-04-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_By', to='myApp.utilisateur'),
        ),
    ]
