# Generated by Django 5.0.3 on 2024-04-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_utilisateur_follows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
