# Generated by Django 5.0.3 on 2024-04-02 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_delete_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='myApp.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.utilisateur')),
            ],
        ),
    ]
